services:
  database:
    image: postgres:18
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: ./backend
    container_name: backend
    environment:
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DB_NAME: ${POSTGRESQL_DB_NAME}
      POSTGRESQL_HOST: database
      POSTGRESQL_PORT: 5432
    depends_on: 
      - database
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:5000/api/emission
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
volumes:
  pgdata:
